// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "e9bc0b3d-4a12-4058-acf6-87303a6b13e5");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1574363636);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1574363756);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1574366756);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1574363396);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1574363276);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1574363516);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1574363996);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1574363876);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 10431);
user_pref("browser.cache.disk.capacity", 788480);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contentblocking.introCount", 5);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1574363131);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{43b1b8ab-a247-415e-95b6-bd7e136dff42}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1574367053797");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1574368881797");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1574366804317");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1574370404317");
user_pref("browser.search.region", "ZA");
user_pref("browser.slowStartup.averageTime", 40547);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190718161435");
user_pref("browser.startup.homepage_override.mstone", "68.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1574363135);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1574363165811");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "bdc9c7cd1fb34bc385436d88b0b63a84");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Thu, 21 Nov 2019 13:19:20 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1574363639);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.0.1");
user_pref("extensions.lastPlatformVersion", "68.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{0f1690d5-9c61-40f5-9a46-ba16d9695406}\",\"addons\":{\"webcompat@mozilla.org\":{\"version\":\"6.1.0\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"28f4af97-bd6f-46a4-95e5-5da7c4c42bf4\",\"fxmonitor@mozilla.org\":\"b21a1d95-77f9-481d-9fe6-37b2c249f002\",\"screenshots@mozilla.org\":\"0db55c05-15c6-466e-bef9-85fd68065c33\",\"webcompat-reporter@mozilla.org\":\"7a8137d7-1231-49d2-88f4-af206069c494\",\"webcompat@mozilla.org\":\"45cf7f26-0148-4aef-8fb5-a926b8581745\",\"default-theme@mozilla.org\":\"b5c05237-3250-4a64-ba8a-439ff5f7530a\",\"google@search.mozilla.org\":\"d15c1d46-5ba2-401f-bd91-3c717dd47cb1\",\"amazondotcom@search.mozilla.org\":\"205be888-bae1-45ff-811c-1773412e1f42\",\"bing@search.mozilla.org\":\"41f377ef-8b53-44b2-9a47-4ef7f700e429\",\"ddg@search.mozilla.org\":\"5d5778b9-8146-4513-8ceb-82c29d943c9a\",\"ebay@search.mozilla.org\":\"1b83dd00-92cd-42e9-b330-aa0cf66ed0df\",\"twitter@search.mozilla.org\":\"15d2aae1-789f-4056-84db-16d61d69f325\",\"wikipedia@search.mozilla.org\":\"81472401-02f6-4344-8cbc-6c663f5eba86\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("identity.fxaccounts.toolbar.accessed", true);
user_pref("idle.lastDailyNotification", 1574363650);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1574363203);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190718161435");
user_pref("media.gmp-manager.lastCheck", 1574363164);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1574363650);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "903ee970-a36d-4b8e-a22b-bfa0f9447466");
user_pref("security.sandbox.plugin.tempDirSuffix", "82faa8ca-557c-4f16-8de4-c366de0dbfb9");
user_pref("services.blocklist.pinning.checked", 1574363160);
user_pref("services.settings.clock_skew_seconds", -153);
user_pref("services.settings.last_etag", "\"1574356142457\"");
user_pref("services.settings.last_update_seconds", 1574363669);
user_pref("services.settings.main.cfr-fxa.last_check", 1574363160);
user_pref("services.settings.main.cfr.last_check", 1574363160);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1574363160);
user_pref("services.settings.main.hijack-blocklists.last_check", 1574363160);
user_pref("services.settings.main.language-dictionaries.last_check", 1574363160);
user_pref("services.settings.main.normandy-recipes.last_check", 1574363160);
user_pref("services.settings.main.sites-classification.last_check", 1574363160);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1574363160);
user_pref("services.settings.security.onecrl.checked", 1574363160);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1574363650);
user_pref("toolkit.startup.last_success", 1574363096);
user_pref("toolkit.telemetry.cachedClientID", "8c4d022d-c08d-4fdd-a5c0-fb8c4c14f280");
user_pref("toolkit.telemetry.previousBuildID", "20190718161435");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
